name: Unit Tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  phpunit-tests:
    name: PHPUnit tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Composer dependencies
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys:
            ${{ runner.os }}-composer-

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          working_dir: PodcastGenerator
          php_version: "8.0"
          php_extensions: gettext xdebug 

      # Run PHPUnit tests
      - name: PHPUnit
        uses: php-actions/phpunit@v3
        with:
          php_version: "8.0"
          configuration: phpunit.xml.dist
          log_junit: test-results/junit.xml
          memory_limit: 256M
        env:
          XDEBUG_MODE: coverage

      # Report coverage
      - name: Clover coverage Report
        uses: danhunsaker/clover-reporter-action@v0.2.17-clover
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clover-file: test-results/clover.xml
